### ISSUE TITLE
Disabled Heroku SSLv3 has broken this gem

### ISSUE THREAD

**Issue by luislew** [heroku/platform-api#17]
This past Thursday (10/16/14), Heroku disabled SSLv3 across all SSL endpoints: https://status.heroku.com/incidents/678

As a result, all API requests using PlatformAPI are currently failing:

```
Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/ssl_socket.rb:60:in `connect'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/ssl_socket.rb:60:in `initialize'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/connection.rb:362:in `new'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/connection.rb:362:in `socket'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/connection.rb:193:in `request_kernel'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/connection.rb:96:in `block in request'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/standard_instrumentor.rb:11:in `instrument'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/excon-0.16.4/lib/excon/connection.rb:95:in `request'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/heroics-0.0.12/lib/heroics/link.rb:60:in `run'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/heroics-0.0.12/lib/heroics/resource.rb:27:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/platform-api-0.2.0/lib/platform-api/client.rb:568:in `info'
```

In order to fix this, Excon needs to make requests using TLSv1.0 or higher.

**Comment by geemus** [comment]
Thanks for the note, sorry it took so long to get back to it. I believe this has been fixed for some time, so cleaning up the issue.
