### ISSUE TITLE
Error on SNI Endpoint Update

### ISSUE THREAD

**Issue by cmunozgar** [heroku/platform-api#90]
Hi there!

I'm trying to update the SSL certificate  programmatically with the SNI Endpoint update function, specifying the APP_NAME, SNI_ENDPOINT_ID, the certificate_chain and the private_key and I'm getting the following error:

    Excon::Error::UnprocessableEntity: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(422 Unprocessable Entity)
	from /usr/local/bundle/gems/excon-0.62.0/lib/excon/middlewares/expects.rb:7:in `response_call'
	from /usr/local/bundle/gems/excon-0.62.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /usr/local/bundle/gems/excon-0.62.0/lib/excon/connection.rb:414:in `response'
	from /usr/local/bundle/gems/excon-0.62.0/lib/excon/connection.rb:263:in `request'
	from /usr/local/bundle/gems/heroics-0.0.25/lib/heroics/link.rb:111:in `request_with_cache'
	from /usr/local/bundle/gems/heroics-0.0.25/lib/heroics/link.rb:66:in `run'
	from /usr/local/bundle/gems/heroics-0.0.25/lib/heroics/resource.rb:28:in `method_missing'
	from /usr/local/bundle/gems/platform-api-2.2.0/lib/platform-api/client.rb:2835:in `update'
	from (irb):6
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'`

Any idea why this is happening? I can list the SNI endpoints, show the info of the SNI Endpoint but can't update it.

Thanks in advance! Greetings!

**Comment by cmunozgar** [comment]
I found out that the private_key that I was sending was not correct. I did find this out when trying to replicate the error using the API through the CURL command. In this case I got an error message.
